x-dev-setup: &dev-setup
  volumes:
    - ./:/usr/src/app:rw

services:
  api-gateway:
    <<: *dev-setup
    command: >
      sh -c "npm run deploy && npm run start:dev"

  auth-service:
    <<: *dev-setup
    command: >
      sh -c "npm run start:dev auth"

  fiat-service:
    <<: *dev-setup
    command: >
      sh -c "npm run start:dev fiat"

  crypto-service:
    <<: *dev-setup
    command: >
      sh -c "npm run start:dev crypto"

  wager-service:
    <<: *dev-setup
    command: >
      sh -c "npm run start:dev wager"