x-test-setup: &test-setup
  volumes:
    - ./:/usr/src/app:rw
  environment:
    - NODE_ENV=test
    - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test-DB?schema=public

services:
  test-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test-DB

  admin-service:
    <<: *test-setup
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    restart: always
    networks:
      - app-network
    env_file:
      - ./.env
    depends_on:
      - test-db
      - nats-server
    command: >
      sh -c "npm run start:dev admin"      

  auth-service:
    <<: *test-setup
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    restart: always
    networks:
      - app-network
      - auth-network
    env_file:
      - ./.env
      - ./apps/auth/.env
    depends_on:
      - test-db
      - auth-redis
      - nats-server
    command: >
      sh -c "npm run start:dev auth"

  auth-redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - ./apps/auth/.env
    networks:
      - auth-network
    command: >
      /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"

  wallet-service:
    <<: *test-setup
    build:
      context: .
      dockerfile: ./apps/wallet/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
      - wallet-network
    env_file:
      - ./.env
      - ./apps/wallet/.env
    depends_on:
      - test-db
      - nats-server
    secrets:
      - platform_wallet_keyphrase
    command: >
      sh -c "npm run start:dev wallet"

  wallet-redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    env_file:
      - ./apps/wallet/.env
    networks:
      - wallet-network
    command: >
      /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"

  wager-service:
    <<: *test-setup
    build:
      context: .
      dockerfile: ./apps/wager/Dockerfile
    restart: always
    ports:
      - "8082:8080"
    env_file:
      - ./.env
      - ./apps/wager/.env
    networks:
      - app-network
      - wager-network
    depends_on:
      - test-db
      - wager-redis
      - nats-server
    command: >
      sh -c "npm run start:dev wager"

  wager-redis:
    image: redis:latest
    restart: always
    ports:
      - "6382:6379"
    env_file:
      - ./apps/wager/.env
    networks:
      - wager-network
    command: >
      /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"

  user-service:
    <<: *test-setup
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    restart: always
    networks:
      - app-network
    env_file:
      - ./.env
    depends_on:
      - test-db
      - nats-server
    command: >
      sh -c "npm run start:dev user"

  nats-server:
    image: nats:latest
    restart: always
    ports:
      - "4222:4222"
    networks:
      - app-network

networks:
  app-network:
  auth-network:
  wager-network:
  wallet-network:

secrets:
  platform_wallet_keyphrase:
    file: phrase.txt