x-dev-setup: &dev-setup
  volumes:
    - ./:/usr/src/app:rw

services:
  api-gateway:
    <<: *dev-setup
    command: >
      sh -c "npm run deploy && npm run start:dev"

  admin-service:
    <<: *dev-setup
    command: >
      sh -c "npm run start:dev admin"

  auth-service:
    <<: *dev-setup
    command: >
      sh -c "npm run start:dev auth"

  wallet-service:
    <<: *dev-setup
    command: >
      sh -c "npm run start:dev wallet"

  user-service:
    <<: *dev-setup
    command: >
      sh -c "npm run start:dev user"

  wager-service:
    <<: *dev-setup
    command: >
      sh -c "npm run start:dev wager"