x-prod-setup: &prod-setup
  environment:
    - NODE_ENV=production
  command: >
    sh -c "npm run deploy && npm run start:prod"

services:
  api-gateway:
    <<: *prod-setup
  admin-service:
    <<: *prod-setup    
  auth-service:
    <<: *prod-setup
  wallet-service:
    <<: *prod-setup
  user-service:
    <<: *prod-setup
  wager-service:
    <<: *prod-setup