x-test-setup: &test-setup
  volumes:
    - ./:/usr/src/app:rw
  environment:
    - DATABASE_URL=postgresql://postgres:postgres@test-db:5432/test-DB?schema=public
    - NATS_URL=nats://nats-server:4222

services:
  test-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test-DB

  test-redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
    command: >
      /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"

  nats-server:
    image: nats:latest
    restart: always
    ports:
      - "4222:4222"

  admin-service:
    <<: *test-setup
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    restart: always
    env_file:
      - ./.env.test
    depends_on:
      - test-db
      - test-redis
      - nats-server
    command: >
      sh -c "npm run start:dev admin"      

  auth-service:
    <<: *test-setup
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    restart: always
    env_file:
      - ./.env.test
    depends_on:
      - test-db
      - test-redis
      - nats-server
    command: >
      sh -c "npm run deploy && npm run start:dev auth"

  wallet-service:
    <<: *test-setup
    build:
      context: .
      dockerfile: ./apps/wallet/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env.test
    depends_on:
      - test-db
      - test-redis
      - nats-server
    secrets:
      - platform_wallet_keyphrase
    command: >
      sh -c "npm run start:dev wallet"

  wager-service:
    <<: *test-setup
    build:
      context: .
      dockerfile: ./apps/wager/Dockerfile
    restart: always
    ports:
      - "8082:8080"
    env_file:
      - ./.env.test
    depends_on:
      - test-db
      - test-redis
      - nats-server
    command: >
      sh -c "npm run start:dev wager"

  user-service:
    <<: *test-setup
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    restart: always
    env_file:
      - ./.env.test
    depends_on:
      - test-db
      - test-redis
      - nats-server
    command: >
      sh -c "npm run start:dev user"

secrets:
  platform_wallet_keyphrase:
    file: phrase.txt