global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: auth-service-metrics
    metrics_path: /api/auth/metrics
    static_configs:
      - targets: [ 'api-gateway:3000' ]

  - job_name: wager-service-metrics
    metrics_path: /api/wagers/metrics
    static_configs:
      - targets: [ 'api-gateway:3000' ]

  - job_name: wallet-service-metrics
    metrics_path: /api/wallet/metrics
    static_configs:
      - targets: [ 'api-gateway:3000' ]